#import "./fragments/ContentFragment.gql"

query BlogListPageQuery($locale: [Locales] = en $id: String) {
  Content(locale: $locale, where: { Ancestors: { eq: $id } }) {
    items {
      ...ContentFragment
      ... on BlogListPage {
        MainBody
      }
    }
  }
}
