#import "./fragments/ContentFragment.gql"

query BlogItemPageQuery($locale: [Locales] = en $id: String) {
  BlogItemPage(locale: $locale, ids: [$id]) {
    items {
      ...ContentFragment
      PageImage {
        Url
      }
      MainBody
    }
  }
}
