#import "./fragments/ContentFragment.gql"

query FolderPageQuery($locale: [Locales] = en $ancestors: String, $limit: Int = 6) {
  Content(
    locale: $locale, 
    where: { Ancestors: { eq: $ancestors } }
    orderBy: { StartPublish: DESC }
    limit: $limit
  ) {
    items {
      ...ContentFragment
      ... on TagPage {
        MainBody
      }
    }
  }
}
