query HomePageQuery($locale: [Locale] = [en]) {
  HomePage(locale: $locale, where: { Name: { eq: "Epi Health" } }) {
    items {
      Name
      ContentLink {
        GuidValue
      }
      MainBody
      MainContentArea {
        ContentLink {
          Expanded {
            Name
            ContentType
            ContentLink {
              GuidValue
            }
          }
        }
      }
    }
  }
}
