#import "./fragments/ContentFragment.gql"
#import "./fragments/ContainerBlockFragment.gql"

query HomePageQuery($locale: [Locales] = [en]) {
  HomePage(locale: $locale, limit: 1) {
    items {
      Name
      ContentLink {
        GuidValue
      }
      MainBody
      MainContentArea {
        ContentLink {
          Expanded {
            ...ContentFragment

            ... on HeroBlock {
              BlockRatio
              BackgroundImage {
                Url
              }
            }
            ... on ContainerBlock {
              ...ContainerBlockFragment
            }
          }
        }
      }
    }
  }
}
