#import "./fragments/ContentFragment.gql"
#import "./fragments/BlockFragment.gql"

query LandingPageQuery($locale: [Locales] = en $id: String) {
  LandingPage(locale: $locale, ids: [$id]) {
    items {
      TopContentArea {
        ContentLink {
          Expanded {
            ...ContentFragment
            ...BlockFragment
          }
        }
      }
      MainContentArea {
        ContentLink {
          Expanded {
            ...ContentFragment
            ...BlockFragment
            ... on ContainerBlock {
              ...ContainerBlockFragment
            }
          }
        }
      }
    }
  }
}
