#import "./fragments/ContentFragment.gql"

query LayoutQuery {
  HomePage(locale: en, where: { ContentType: { eq: "Page" }, RouteSegment: { eq: "home" } }) {
    items {
      Name
      RouteSegment
      Url
      ContentType
      _children {
        Content {
          items {
            ...ContentFragment
            _children {
              Content {
                items {
                  ...ContentFragment
                }
              }
            }
          }
        }
      }
    }
  }
}
