#import "./fragments/LocationItemFragment.gql"

query LocationItemQuery($locale: [Locale] = [EN], $route: String) {
  LocationItemPage(locale: $locale, where: { Url: { like: $route } }) {
    items {
      ...LocationItemFragment
      MainBody
    }
  }
}
