#import "./Fragments.gql"

query LocationListQuery(
  $locale: [Locale] = [en]
  $continents: [String] = []
  $countries: [String] = []
  $minAvgTemp: Float = -50
  $maxAvgTemp: Float = 50
  $fullTextSearch: String = ""
) {
  LocationListPage(locale: $locale) {
    items {
      Name
      MainBody
      _children {
        LocationItemPage(
          where: {
            AvgTemp: { gte: $minAvgTemp, lte: $maxAvgTemp }
            Country: { in: $countries }
            Continent: { in: $continents }
            _fulltext: { contains: $fullTextSearch }
          }
        ) {
          items {
            ...LocationItemFragment
          }
          facets {
            Country(orderType: VALUE, orderBy: ASC, limit: 100) {
              name
              count
            }
            Continent(orderType: VALUE, orderBy: ASC) {
              name
              count
            }
            AverageTemperature: AvgTemp(
              ranges: [
                { from: -50, to: -40 }
                { from: -40, to: -30 }
                { from: -30, to: -20 }
                { from: -20, to: -10 }
                { from: -10, to: 0 }
                { from: 0, to: 10 }
                { from: 20, to: 30 }
                { from: 30, to: 40 }
                { from: 40, to: 50 }
              ]
            ) {
              name
              count
            }
          }
        }
      }
    }
  }
}
