#import "./fragments/LocationItemFragment.gql"

query LocationItemQuery($locale: [Locales] = en $id: String) {
  LocationItemPage(locale: $locale, ids: [$id]) {
    items {
      ...LocationItemFragment
      MainBody
    }
  }
}
