#import "./fragments/StandardPageFragment.gql"

query PageListQuery($locale: [Locales] = en $ancestors: String, $limit: Int) {
  StandardPage(
    locale: $locale, 
    where: { Ancestors: { eq: $ancestors } }
    orderBy: { StartPublish: DESC }
    limit: $limit
  ) {
    items {
      ...StandardPageFragment
    }
  }
}
