#import "./fragments/ContentFragment.gql"

query SearchQuery($text: String) {
  Content(where: { _fulltext: { like: $text }, ContentType: { eq: "Page" } }) {
    items {
      ...ContentFragment
      Language {
        DisplayName
        Name
      }
      _fulltext
    }
  }
}
