#import "./fragments/StandardPageFragment.gql"

query StandardPageQuery($id: String) {
  StandardPage(ids: [$id]) {
    items {
      ...StandardPageFragment
      MainBody
      MainContentArea {
        ContentLink {
          Expanded {
            ContentType
            ... on StandardPage {
              ...StandardPageFragment
            }
          }
        }
      }
    }
  }
}
